//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2BanlistCore.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanlistDbContext : DbContext
    {
        public BanlistDbContext()
            : base("name=BanlistDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    
        public DbSet<Matches> Matches { get; set; }
        public DbSet<SteamIds> SteamIds { get; set; }
        public DbSet<MatchPlayers> MatchPlayers { get; set; }
    }
}
