//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2BanlistCore.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPlayers
    {
        public int Id { get; set; }
        public int PlayerIndex { get; set; }
    
        public virtual Matches Match { get; set; }
        public virtual SteamIds SteamId { get; set; }
    }
}
